---
kind: ConfigMap
apiVersion: v1
metadata:
  namespace: "{{ .Release.Namespace }}"
  name: "{{ .Chart.Name }}-config"
  labels:
    app.kubernetes.io/name: "{{ .Chart.Name }}"
    app.kubernetes.io/component: "app"
    app.kubernetes.io/part-of: "{{ .Chart.Name }}"
data:
  application.properties: |
    #
    # Copyright (c) 2021 Kaiserpfalz EDV-Service, Roland T. Lichti
    #
    # This program is free software: you can redistribute it and/or modify
    # it under the terms of the GNU General Public License as published by
    # the Free Software Foundation, either version 3 of the License, or
    # (at your option) any later version.
    #
    # This program is distributed in the hope that it will be useful,
    # but WITHOUT ANY WARRANTY; without even the implied warranty of
    # MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    # GNU General Public License for more details.
    #
    # You should have received a copy of the GNU General Public License
    # along with this program.  If not, see <http://www.gnu.org/licenses/>.
    #

    server.port=${DELPHI_COUNCIL_IS_APP_SERVICE_PORT:8080}
    vaadin.compatibilityMode=false
    spring.web.locale=de_DE
    spring.servlet.multipart.enabled=false

    logging.level.de.paladinsinn=info
    logging.level.de.kaiserpfalzedv=warn
    logging.level.org.atmosphere=warn
    logging.level.liquibase=warn
    logging.level.org.springframework=warn
    logging.level=warn

    spring.datasource.url=jdbc:mariadb://delphi-council-is-db:3306/${DB_DATABASE}
    spring.datasource.username=${DB_USER}
    spring.datasource.password=${DB_PASSWORD}
    spring.liquibase.enabled=true
    spring.liquibase.change-log=classpath:/db/changelog/db.changelog-master.xml
    spring.jpa.hibernate.ddl-auto=validate
    spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

    mail.from.user=${MAIL_FROM_NAME}
    mail.from.address=${MAIL_FROM_ADDRESS}
    spring.mail.host=${MAIL_HOST}
    spring.mail.port=${MAIL_PORT}
    spring.mail.username=${MAIL_USER}
    spring.mail.password=${MAIL_PASSWORD}
    spring.mail.properties.mail.smtp.auth=true
    spring.mail.properties.mail.smtp.starttls.enable=true
    spring.mail.properties.mail.smtp.connectiontimeout=5000
    spring.mail.properties.mail.smtp.timeout=3000
    spring.mail.properties.mail.smtp.writetimeout=5000
    spring.mail.templates.path=/deployments/mail