---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: "{{ .Release.Namespace }}"
  name: delphi-council-db
  labels:
    app.kubernetes.io/name: "{{ .Chart.Name }}"
    app.kubernetes.io/component: "db"
    app.kubernetes.io/part-of: "{{ .Chart.Name }}"
    app.kubernetes.io/version: "{{ .Chart.AppVersion }}"
  finalizers:
    - kubernetes.io/pvc-protection
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: "{{ .Values.db.storagesize }}"
  storageClassName: local-hdd
