{{- $fullName := include "tomb.fullname" . -}}
  {{- $svcPort := .Values.service.port -}}
---
kind: Ingress
apiVersion: networking.k8s.io/v1
metadata:
  name: {{ $fullName }}
  labels:
    {{- include "tomb.labels" . | nindent 4 }}
spec:
  tls:
    - hosts:
      {{- range .Values.hosts.hosts }}
      - {{ . | quote }}
      {{- end }}
      secretName: {{ $fullName }}-tls
  rules:
  {{- range .Values.hosts.hosts }}
  - host: {{ . | quote }}
    http:
      paths:
        - path: /
          pathType: ImplementationSpecific
          backend:
            service:
              name: {{ $fullName }}
              port:
                number: {{ $svcPort }}
  {{- end }}
