{{ $fullname := include "tomb.fullname" . }}
---
kind: Secret
apiVersion: v1
metadata:
  name: {{ $fullname }}-mongodb
  annotations:
    template.openshift.io/expose-scheme: '{.data[''scheme'']}'
    template.openshift.io/expose-host: '{.data[''host'']}'
    template.openshift.io/expose-tls: '{.data[''tls'']}'
    template.openshift.io/expose-parameters: '{.data[''parameters'']}'
    template.openshift.io/expose-replicaset: '{.data[''replicaset'']}'
    template.openshift.io/expose-auth-source: '{.data[''auth-source'']}'
    template.openshift.io/expose-database: '{.data[''database'']}'
    template.openshift.io/expose-user: '{.data[''user'']}'
    template.openshift.io/expose-password: '{.data[''password'']}'
  labels:
    {{- include "tomb.labels" . | nindent 4 }}
    app.kubernetes.io/component: "mongodb"
stringData:
  scheme: "{{ .Values.mongodb.scheme }}"
  hosts: "{{ .Values.mongodb.hosts }}"
  tls: "{{ .Values.mongodb.tls }}"
  parameters: "{{ .Values.mongodb.parameters }}"
  replicaset: "{{ .Values.mongodb.replicaset }}"
  auth-source: "{{ .Values.mongodb.authSource }}"
  database: "{{ .Values.mongodb.database }}"
  user: "{{ .Values.mongodb.user }}"
  password: "{{ .Values.mongodb.password }}"
---
kind: Secret
apiVersion: v1
metadata:
  name: {{ $fullname }}-discord
  annotations:
    template.openshift.io/expose-applicationId: '{.data[''applicationId'']}'
    template.openshift.io/expose-permissionInteger: '{.data[''permissionInteger'']}'
    template.openshift.io/expose-token: '{.data[''token'']}'
    template.openshift.io/expose-clientId: '{.data[''clientId'']}'
    template.openshift.io/expose-clientSecret: '{.data[''clientSecret'']}'
  labels:
    {{- include "tomb.labels" . | nindent 4 }}
    app.kubernetes.io/component: "discord"
stringData:
  applicationId: "{{ .Values.discord.applicationId }}"
  permissionInteger: "{{ .Values.discord.permissionInteger }}"
  token: "{{ .Values.discord.token }}"
  clientId: "{{ .Values.discord.clientId }}"
  clientSecret: "{{ .Values.discord.clientSecret }}"
